### ISSUE TITLE
Error while serving

### ISSUE THREAD

**Issue by xplosionmind** [rknightuk/eleventy-pagefind-demo#1]
Hi @rknightuk! Thanks **so much** for the great insights you gave by publishing this repository.

Unfortunately, I stumble upon this error while serving my website. Would it be I did not install a required dependency? (maybe the one providing the `execSync` function?)

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] execSync is not defined (via ReferenceError)
[11ty] 
[11ty] Original error stack trace: ReferenceError: execSync is not defined
[11ty]     at AsyncEventEmitter.<anonymous> (/home/tommi/tommi.space/.eleventy.js:204:3)
[11ty]     at /home/tommi/tommi.space/node_modules/@11ty/eleventy/src/Util/AsyncEventEmitter.js:19:61
[11ty]     at Array.map (<anonymous>)
[11ty]     at AsyncEventEmitter.emit (/home/tommi/tommi.space/node_modules/@11ty/eleventy/src/Util/AsyncEventEmitter.js:19:34)
[11ty]     at Eleventy.executeBuild (/home/tommi/tommi.space/node_modules/@11ty/eleventy/src/Eleventy.js:1209:32)
[11ty]     at async Eleventy.watch (/home/tommi/tommi.space/node_modules/@11ty/eleventy/src/Eleventy.js:1014:18)
```

**Comment by xplosionmind** [comment]
Got it!

I needed to add `const execSync = require('child_process').execSync;` before. Solution found [here](https://stackoverflow.com/questions/4443597/node-js-execute-system-command-synchronously).
